## Матричный метод

In [4]:
import numpy as np

* -x0+2x1-3x=4
* 2x0+x1+2x2=3
* 3x0-2x1-x2=9

Создадим матрицу

In [5]:
K = np.array([[-1., 2., -3.], [2., 1., 2.], [3., -2., -1.]])
K

array([[-1.,  2., -3.],
       [ 2.,  1.,  2.],
       [ 3., -2., -1.]])

Создадим вектор

In [6]:
L = np.array([4., 3., 9.])
L

array([4., 3., 9.])

Для решения системы воспользуемся функцией numpy.linalg.solve

In [7]:
np.linalg.solve(K, L)

array([ 2.91176471,  0.76470588, -1.79411765])

Ответ: 2.91176471,  0.76470588, -1.79411765