## Свойства матричных вычислений

In [6]:
import numpy as np

In [7]:
l = [[9, 13, 5, 2], [1, 11, 7, 6], [3, 7, 4, 1], [6, 0, 7, 10]]
A = np.array(l)
A

array([[ 9, 13,  5,  2],
       [ 1, 11,  7,  6],
       [ 3,  7,  4,  1],
       [ 6,  0,  7, 10]])

In [8]:
k = [[3, 1, 13, 1], [1, 2, 5, 2], [4, 6, 8, 12], [5, 4, 2, 12]]
B = np.array(k)
B

array([[ 3,  1, 13,  1],
       [ 1,  2,  5,  2],
       [ 4,  6,  8, 12],
       [ 5,  4,  2, 12]])

In [9]:
k = [[4, 2, 5, 7], [1, 5, 3, 11], [16, 24, 8, 9], [8, 16, 0, 13]]
C = np.array(k)
C

array([[ 4,  2,  5,  7],
       [ 1,  5,  3, 11],
       [16, 24,  8,  9],
       [ 8, 16,  0, 13]])

Транспонирование матрицы:

In [10]:
A.transpose()

array([[ 9,  1,  3,  6],
       [13, 11,  7,  0],
       [ 5,  7,  4,  7],
       [ 2,  6,  1, 10]])

In [11]:
A.T

array([[ 9,  1,  3,  6],
       [13, 11,  7,  0],
       [ 5,  7,  4,  7],
       [ 2,  6,  1, 10]])

Дважды транспонированная матрица равна исходной матрице:

In [12]:
(A.T).T

array([[ 9, 13,  5,  2],
       [ 1, 11,  7,  6],
       [ 3,  7,  4,  1],
       [ 6,  0,  7, 10]])

Транспонирование суммы матриц равно сумме транспонированных матриц:

In [13]:
(A+B).T

array([[12,  2,  7, 11],
       [14, 13, 13,  4],
       [18, 12, 12,  9],
       [ 3,  8, 13, 22]])

In [14]:
A.T+B.T

array([[12,  2,  7, 11],
       [14, 13, 13,  4],
       [18, 12, 12,  9],
       [ 3,  8, 13, 22]])

Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [15]:
(A.dot(B)).T

array([[ 70,  72,  37,  96],
       [ 73,  89,  45,  88],
       [226, 136, 108, 154],
       [119, 179,  77, 210]])

In [16]:
(B.T).dot(A.T)

array([[ 70,  72,  37,  96],
       [ 73,  89,  45,  88],
       [226, 136, 108, 154],
       [119, 179,  77, 210]])

Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [17]:
t = 4

In [18]:
(t * A).T

array([[36,  4, 12, 24],
       [52, 44, 28,  0],
       [20, 28, 16, 28],
       [ 8, 24,  4, 40]])

In [19]:
t * (A.T)

array([[36,  4, 12, 24],
       [52, 44, 28,  0],
       [20, 28, 16, 28],
       [ 8, 24,  4, 40]])

Определители исходной и транспонированной матрицы совпадают:

In [26]:
 A_det = np.linalg.det(A)
print(format(A_det, '.9g'))

1686


In [28]:
A_T_det = np.linalg.det(A.T)
print(format(A_T_det, '.9g'))

1686


Умножение матрицы на число


In [29]:
7 * A

array([[63, 91, 35, 14],
       [ 7, 77, 49, 42],
       [21, 49, 28,  7],
       [42,  0, 49, 70]])

Произведение единицы и любой заданной матрицы равно заданной матрице:

In [30]:
1 * A

array([[ 9, 13,  5,  2],
       [ 1, 11,  7,  6],
       [ 3,  7,  4,  1],
       [ 6,  0,  7, 10]])

Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

In [31]:
0 * A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

 Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [32]:
(3 + 5) * A

array([[ 72, 104,  40,  16],
       [  8,  88,  56,  48],
       [ 24,  56,  32,   8],
       [ 48,   0,  56,  80]])

In [34]:
3 * A + 5 * A

array([[ 72, 104,  40,  16],
       [  8,  88,  56,  48],
       [ 24,  56,  32,   8],
       [ 48,   0,  56,  80]])

Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [35]:
(3 * 5) * A

array([[135, 195,  75,  30],
       [ 15, 165, 105,  90],
       [ 45, 105,  60,  15],
       [ 90,   0, 105, 150]])

In [36]:
3 * (5 * A)

array([[135, 195,  75,  30],
       [ 15, 165, 105,  90],
       [ 45, 105,  60,  15],
       [ 90,   0, 105, 150]])

Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [37]:
4 * (A + B)

array([[48, 56, 72, 12],
       [ 8, 52, 48, 32],
       [28, 52, 48, 52],
       [44, 16, 36, 88]])

In [38]:
4 * A + 4 * B

array([[48, 56, 72, 12],
       [ 8, 52, 48, 32],
       [28, 52, 48, 52],
       [44, 16, 36, 88]])

Сложение матриц


In [39]:
A + B

array([[12, 14, 18,  3],
       [ 2, 13, 12,  8],
       [ 7, 13, 12, 13],
       [11,  4,  9, 22]])

In [40]:
B + A

array([[12, 14, 18,  3],
       [ 2, 13, 12,  8],
       [ 7, 13, 12, 13],
       [11,  4,  9, 22]])

In [41]:
A + (B + C)

array([[16, 16, 23, 10],
       [ 3, 18, 15, 19],
       [23, 37, 20, 22],
       [19, 20,  9, 35]])

In [42]:
(A + B) + C

array([[16, 16, 23, 10],
       [ 3, 18, 15, 19],
       [23, 37, 20, 22],
       [19, 20,  9, 35]])

In [44]:
A + (-1)*A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Диаграмма матричного умножения


In [45]:
A.dot(B)

array([[ 70,  73, 226, 119],
       [ 72,  89, 136, 179],
       [ 37,  45, 108,  77],
       [ 96,  88, 154, 210]])

Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [46]:
A.dot(B.dot(C))

array([[4921, 7833, 2377, 4874],
       [3985, 6717, 1715, 5034],
       [2537, 4123, 1184, 2727],
       [4616, 7688, 1976, 5756]])

In [47]:
(A.dot(B)).dot(C)

array([[4921, 7833, 2377, 4874],
       [3985, 6717, 1715, 5034],
       [2537, 4123, 1184, 2727],
       [4616, 7688, 1976, 5756]])

Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [48]:
A.dot(B+C)

array([[215, 308, 350, 396],
       [247, 410, 230, 448],
       [128, 198, 176, 224],
       [312, 428, 240, 445]])

In [49]:
A.dot(B)+A.dot(C)

array([[215, 308, 350, 396],
       [247, 410, 230, 448],
       [128, 198, 176, 224],
       [312, 428, 240, 445]])

Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:

In [50]:
A.dot(B)

array([[ 70,  73, 226, 119],
       [ 72,  89, 136, 179],
       [ 37,  45, 108,  77],
       [ 96,  88, 154, 210]])

In [51]:
B.dot(A)

array([[ 73, 141,  81,  35],
       [ 38,  70,  53,  39],
       [138, 174, 178, 172],
       [127, 123, 145, 156]])

Произведение заданной матрицы на единичную равно исходной матрице:

In [52]:
E = np.matrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1')
E.dot(A)

matrix([[ 9, 13,  5,  2],
        [ 1, 11,  7,  6],
        [ 3,  7,  4,  1],
        [ 6,  0,  7, 10]])

In [53]:
A.dot(E)

matrix([[ 9, 13,  5,  2],
        [ 1, 11,  7,  6],
        [ 3,  7,  4,  1],
        [ 6,  0,  7, 10]])

Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [54]:
Z = np.matrix('0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0')
Z.dot(A)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [55]:
A.dot(Z)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

Определитель матрицы

In [56]:
np.linalg.det(A)

1685.9999999999986

Определитель матрицы остается неизменным при ее транспонировании:

In [60]:
round(np.linalg.det(A), 3)

1686.0

In [61]:
round(np.linalg.det(A.T), 3)

1686.0

Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [62]:
N = np.matrix('1 0 1; 0 0 1; 21 2 1')
np.linalg.det(N)

-2.0

При перестановке строк матрицы знак ее определителя меняется на
противоположный:

In [66]:
N = np.matrix('9 1 3; 4 9 1; 14 9 1')
round(np.linalg.det(N), 3)

-260.0

In [67]:
N = np.matrix('13 9 11; 1 4 1; 16 11 6')
round(np.linalg.det(N), 3)

-324.0

Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [68]:
N = np.matrix('9 8 7; 5 6 4; 9 8 7')
np.linalg.det(N)

0.0

Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [69]:
N = np.matrix('3 6 1; 4 1 2; 9 11 11')
k = 3
M = N.copy()
M[2, :] = k * M[2, :]
print(M)

[[ 3  6  1]
 [ 4  1  2]
 [27 33 33]]


In [70]:
det_N = round(np.linalg.det(N), 3)
det_M = round(np.linalg.det(M), 3)

In [71]:
det_N * k

-462.0

In [72]:
det_M

-462.0

Если все элементы строки или столбца можно представить как сумму двух
слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих
матриц:

In [73]:
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[ 9 13  5  2]
 [ 2 13 12  8]
 [ 3  7  4  1]
 [ 6  0  7 10]]


In [74]:
A

array([[ 9, 13,  5,  2],
       [ 1, 11,  7,  6],
       [ 3,  7,  4,  1],
       [ 6,  0,  7, 10]])

In [75]:
B

array([[ 3,  1, 13,  1],
       [ 1,  2,  5,  2],
       [ 4,  6,  8, 12],
       [ 5,  4,  2, 12]])

In [78]:
round(np.linalg.det(C), 3)

1221.0

In [79]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

1856.0

Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:

In [80]:
C = A.copy()
C[1, :] = C[1, :] + 3 * C[0, :]
A

array([[ 9, 13,  5,  2],
       [ 1, 11,  7,  6],
       [ 3,  7,  4,  1],
       [ 6,  0,  7, 10]])

In [81]:
C

array([[ 9, 13,  5,  2],
       [28, 50, 22, 12],
       [ 3,  7,  4,  1],
       [ 6,  0,  7, 10]])

In [82]:
round(np.linalg.det(A), 3)

1686.0

In [83]:
round(np.linalg.det(C), 3)

1686.0

Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю:

In [84]:
A[1, :] = A[0, :] + 3 * A[2, :]
round(np.linalg.det(A), 3)

-0.0

Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [85]:
A[1, :] = 2 * A[0, :]
A

array([[ 9, 13,  5,  2],
       [18, 26, 10,  4],
       [ 3,  7,  4,  1],
       [ 6,  0,  7, 10]])

In [86]:
round(np.linalg.det(A), 3)

0.0

Обратная матрица

Обратная матрица обратной матрицы есть исходная матрица:

In [90]:
N = np.matrix('6 9; -12 18')
np.linalg.inv(N)

matrix([[ 0.08333333, -0.04166667],
        [ 0.05555556,  0.02777778]])

Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

In [91]:
np.linalg.inv(N.T)

matrix([[ 0.08333333,  0.05555556],
        [-0.04166667,  0.02777778]])

In [92]:
(np.linalg.inv(N)).T

matrix([[ 0.08333333,  0.05555556],
        [-0.04166667,  0.02777778]])

Обратная матрица произведения матриц равна произведению обратных матриц:

In [93]:
M = np.matrix('3. 6.; 5. 10.')
N = np.matrix('-4. 8.; 3. -9.')
np.linalg.inv(M.dot(N))

matrix([[-4.50359963e+15,  2.70215978e+15],
        [-9.00719925e+14,  5.40431955e+14]])

In [94]:
np.linalg.inv(N).dot(np.linalg.inv(M))

matrix([[ 3.75299969e+15, -2.25179981e+15],
        [ 7.50599938e+14, -4.50359963e+14]])